# This is the configuration file for the netlify preview deploys
# See https://www.netlify.com/docs/netlify-toml-reference/ for more

[build]
  publish = "dist/"

[[redirects]]
  from = "/"
  to = "/demo/src/"
